= Public Review of the Biometric iTC PP-Module & Supporting Document
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:revnumber: 0.2
:revdate: 2019-05-30
:xrefstyle: full

== Introduction

This is an announcement of a public review period for the PP-Module and PP-Module Supporting Document from the BIO-iTC. By design these documents do not provide information about the methodology for performing Presentation Attack Detection. These are being handled as a toolkit which can be updated separately (and ideally more rapidly) without needing changes to the PP-Module and Supporting Document.

This document will provide information about where to find the documents, how to provide feedback and information about the current status of the documents.

== Review Status Phase
The documents listed here are in the *Public Review Draft* phase.

Publication Date:: May 15, 2019 (placeholders)
End of Comment Period:: June 30, 2019

== Documents for Review

The following are the documents are included in this Public Review:

.Documents
[[DocTable]]
|===
|Title |Version |Link

|collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device -
|0.8
|https://www.commoncriteriaportal.org/communities/Bio.cfm <link to comment spreadsheet>

|PP-Configuration for Protection Profile for Mobile Device Fundamentals and collaborative Protection Profile Module for Mobile biometric enrolment and verification - for unlocking the device -
|0.8
|https://www.commoncriteriaportal.org/communities/Bio.cfm <link to comment spreadsheet>

|Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device -
|0.3
|https://www.commoncriteriaportal.org/communities/Bio.cfm <link to comment spreadsheet>

|Toolbox Overview for Testing Compliance for Mobile Biometric Enrolment and Verification
|0.3
|https://www.commoncriteriaportal.org/communities/Bio.cfm <link to comment spreadsheet>

|===

== Document Release Process
The BIO-iTC follows the document release process below for the publication of documents. Generally the PP (PP-Module and PP-Configuration) and SD would be released at the same time.

[ditaa]
....
                                  
    +----------+    +----------+   +----------+   +----------+   +----------+
    |          |    |  cYEL    |   | Public   |   |          |   | Public   |
    | Internal |    |  Public  |   | Review   |   |  Public  |   | Review   |
    |  Draft   |--> |  Review  |-->| Draft 1  |-->|  Review  |-->| Draft 2  |-+
    |          |    |  Draft 1 |   | Update   |   |  Draft 2 |   | Update   | |
    |          |    |  (45d)   |   | (60d)    |   |  (45d)   |   | (60d)    | |
    +----------+    +----------+   +----------+   +----------+   +----------+ |
                                                                              |
            +-----------------------------------------------------------------+
            |   +----------+   +----------+   +-----------+
            |   |          |   |          |   |           |
            |   | Proposed |   | Proposed |   | Final     |
            +-->|  Draft   |-->|  Update  |-->| Document  |
                |          |   |          |   | Published |
                | (30d)    |   | (10d)    |   |           |
                +----------+   +----------+   +-----------+
....

.Review Timeline
[[timeline]]
|===
|Phase |Time |Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Public Review Draft 1
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 1 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 2 (Optional)
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 2 Update (Optional)
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Proposed Draft
|30 days
|iTC has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|iTC reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

The iTC may decide, based on the comments received during the Public Review Draft 1 period, that a Public Review Draft 2 period is needed. Public announcement of a second review draft or a proposed draft will be made once all comments have been addressed.

=== Review Process
There are two ways to contribute comments and suggestions to the iTC. The first is through GitHub, the second by spreadsheet. It should be noted however that comments that are received via the spreadsheet will be added to the github platform to allow for a comprehensive discussion. Also, feedback for comments is only provided via the answers in the github comments. 

Each comment should have a suggested resolution be proposed if a change is needed to the document.

==== GitHub Review Process
To use GitHub to submit comments, you must have a GitHub account (and it is assumed you know how to use GitHub). Each comment should be submitted as an individual https://github.com/biometricITC/cPP-biometrics/issues[Issue] with the Label "Public Review" assigned. Pull Requests created for any issues will be linked to these Issues for tracability.

==== Spreadsheet Review Process
Along with the link in <<DocTable>> for each document is a link to the spreadsheet to be used for comments. Email the spreadsheets to <some email address>.

== Additional Notes
The documents under review are the current state of output. Two major areas of discussion within the iTC that are still under consideration within are noted below. 

Comments on these specific topics can be made separately.

=== Publish as PP-Module or PP
The original focus for the iTC was to create a standalone PP that would be evaluated separately that defines security requirements to provide the secure environment for the biometric enrolment and verification. Later the iTC modified the PP into a PP-Module for somewhat easier integration with the MDFPP (the primary target device at this time).

The iTC is considering several possible options for the final output, including, if necessary, releasing both a PP and a PP-Module sharing resources where appropriate. The iTC will also consider appropriate PP-Configurations for handling integration with other PPs.

=== AVA_VAN Review
The iTC has been considering the appropriate amount of vulnerability assessment for biometric systems. As a group, the iTC has reached out to the supporting and interested schemes for assistance in resolving the issues that have been raised regarding the inclusion of AVA_VAN. The iTC is waiting for feedback and direction from the schemes involved on the next steps related to this issue (and it will likely have an impact on the PP or PP-Module question as well).

In the Supporting Document, the following sections are directly related to the AVA_VAN discussions that are ongoing:

 - 5.6. Class AVA: Vulnerability Assessment
 - 6.3. EA for AVA_VAN.1 (Vulnerability survey)

Comments to these two sections will be reviewed, but any changes will not be performed until after the AVA_VAN discussions with the schemes are complete, at which point any comments will be further reviewed based on the updated document.

=== Number of Subjects in PAD Testing
While the iTC is still working on the PAD toolboxes, the Toolbox Overview has been written to provide a consistent framework for tests.

The iTC is specifically interested in comments regarding the appropriate number of subjects which should be required for each test. 
