 
= Tooblox for testing compliance to cPP for Mobile biometric enrolment and verification 
:showtitle:
:toc:
:sectnums:
:imagesdir: images
:revnumber: 0.2
:revdate: 2019-01-24

== Introduction
This document an its child documents contains a toolbox of Presentation Attack Species (PAS) for various biometric modalities. This toolbox shall be used to test the PAD functionality of a TOE during an evaluation in compliance to <<cPP>>.

This toolbox document shall be used to test for the implementation of the SFR FIA_MBV_EXT.3 from <<cPP>>
It contains content for the following biometric modalities 

* Iris
* Face
* Fingerprint

It should be noted that the toolbox as contained in this document focusses on a functional approach of testing as required by the assurance component ATE_IND.1_. Each toolbox contains the state of the art of the Presentation Attack Instruments of its respective modality. A TOE compliant to <<cPP>> is expected to reliably recognize these PAI. The functional approach of the toolboxes is however not suitable for any test in the context of AVA_VAN. 

The following chapter introduces the overall test approach

== Overall test approach
Then testing approach bases on the following assumptions and principles

* As it could not be assumed that every TOE will return a dedicated result for the PAD functionality, success for an presentation attack is defined for the whole biometric functionality, including the matcher. This means that - in order to succesfully overcome the TOE by the use of an artefact - a genuine person (the tester) has to be enrolled into the TOE, an artefact has to be created for the corresponding biometric modality of the tester and the artefact has to produce a match (i.e. a succesfull verification)
* more?

=== Preparational phase
Before the actual test can start, the following pre-requisites need to be met:
* It has to be ensured that the subject whose biometric data is used to produce the artefacts for testing is enrolled into the TOE. Successful enrollment needs to be documented and verified by performing at least 5 genuine transactions with the TOE. No errors shall occur during the 5 genuine transactions. If any errors occur, the enrollment process shall be repeated. In case of repeated errors, it should be considered to use a different biometric characteristic (this could e.e. mean to use a different finger of a subject or even use a different subject).

=== PAI production 
* The tester shall produce the amount of PAI as defined by the child document. 
* The production of each PAI shall be documented in a manner that the production can be reproduced. 
* Each produced artefact shall be identified by a unique identifier. This identifier shall be be attached to the artefact at all times (as far as this is possible without destroying the artefact)
* 

=== Test 
The actual test of each PAI shall be conducted as follows:
* The artefact shall be applied to the TOE 10 times
** If the TOE matches the previously enrolled user by the use of the artefact, the attempt is considered a fail 
** If the TOE rejects the attempt, this is considered being a pass

=== Pass criteria
The following pass criteria shall be applied if no other criteria are defined in the child documents of this document. 

A TOE passes the test if and only if it reliably defeats the use of *all artefacts* that have to be built according to the toolbox. This means that none of the artefacts must be able to reproducibly overcome the TOE. 

To reproducibly overcome the TOE by the use of a *certain artefact* in the outlined test scneario is defined as follows:

* If a certain PAI does not match in any of its 10 attempts, the TOE passes this PAI. 
* If a certain PAI matches 1 time out of 10, the TOE passes this PAI. 
* If a certain PAI matches 2 times out of 10, an additional 10 attempts shall be added to the test
* If a certain PAI matches 3 times or more (either of the 10 attempts or of the extended set of 20 attempts), the TOE fails that PAI



= Literature

- [[[cPP]]] cPP for Mobile biometric enrolment and verification for unlocking the device

